# Generated by Django 5.1.3 on 2024-12-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtosalon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
